version: '2'
services:
  app:
    build:
      context: .
    image: xdebug-example:latest
    volumes:
     - ./app:/var/www/html
    command: /bin/sh /tmp/start.sh
    ports:
     - "80:80"
  mysql:
    restart: always
    image: mysql:5
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/data:/var/lib/mysql
    # - ./mysql/conf.d:/etc/mysql/conf.d
    environment: 
    - MYSQL_ROOT_PASSWORD=thisismymysql1